---
- name: Check if we already have cachetool.
  stat:
    path: "{{ cachetool_bin }}"
  register: cachetool_global
  when:
    - deploy_operation == 'deploy'

- name: Ensure bin directory exists.
  file:
    path: "{{ cachetool_bin | dirname }}"
    state: directory
  when:
    - deploy_operation == 'deploy'

- name: "Download cachetool version {{ cachetool.version }} installer."
  get_url:
    url: "http://gordalina.github.io/cachetool/downloads/cachetool-{{ cachetool.version }}.phar"
    dest: "{{ cachetool_bin }}"
    mode: 0755
  when:
    - deploy_operation == 'deploy'
    - not cachetool_global.stat.exists
    - cachetool.version is defined
    - cachetool.version | length > 0

- name: Install cachetool depending on php version used
  block:
    - name: Get latest php installed
      ansible.builtin.shell:
        cmd: "ls /etc/php/ | tail -1 | sed -e 's/\.//g"
      register: _php_version_str

    - set_fact:
        _php_version_int: "{{ _php_version_str | int }}"
    - debug:
        msg: "{{ _php_version_int }}"

    - name: "PHP is >= 81. > Downloading latest cachetool installer."
      get_url:
        url: "http://gordalina.github.io/cachetool/downloads/cachetool.phar"
        dest: "{{ cachetool_bin }}"
        mode: 0755
      when:
        - _php_version_int | int >= 81

    - name: "PHP is 8.0. Downloading cachetool version 8.5.0 installer."
      get_url:
        url: "http://gordalina.github.io/cachetool/downloads/cachetool-8.5.0.phar"
        dest: "{{ cachetool_bin }}"
        mode: 0755
      when:
        - _php_version_int == 80

    - name: "PHP is >=7.3. Downloading cachetool version 7.1.0 installer."
      get_url:
        url: "http://gordalina.github.io/cachetool/downloads/cachetool-7.1.0.phar"
        dest: "{{ cachetool_bin }}"
        mode: 0755
      when:
        - _php_version_int >= 73
        - _php_version_int < 80

    - name: "PHP is 7.2. Downloading cachetool version 5.1.3 installer."
      get_url:
        url: "http://gordalina.github.io/cachetool/downloads/cachetool-5.1.3.phar"
        dest: "{{ cachetool_bin }}"
        mode: 0755
      when:
        - _php_version_int == 72

    - name: "PHP is 7.1. Downloading cachetool version 4.1.1 installer."
      get_url:
        url: "http://gordalina.github.io/cachetool/downloads/cachetool-4.1.1.phar"
        dest: "{{ cachetool_bin }}"
        mode: 0755
      when:
        - _php_version_int == 72

    - name: "PHP version is too old.. Downloading cachetool version 3.2.2 installer."
      get_url:
        url: "http://gordalina.github.io/cachetool/downloads/cachetool-3.2.2.phar"
        dest: "{{ cachetool_bin }}"
        mode: 0755
      when:
        - _php_version_int < 72

  when:
    - deploy_operation == 'deploy'
    - not cachetool_global.stat.exists
    - cachetool.version is not defined
