---
- name: Initial housekeeping tasks.
  when: deploy_operation == 'deploy'
  block:
    - name: Remove previous cachetool if exists.
      ansible.builtin.file:
        path: "{{ cachetool_bin }}"
        state: absent

    - name: Ensure bin directory exists.
      ansible.builtin.file:
        path: "{{ cachetool_bin | dirname }}"
        state: directory

- name: Download cachetool depending on latest php version installed. # If not specified manually, according to https://github.com/gordalina/cachetool#compatibility
  when:
    - deploy_operation == 'deploy'
    - cachetool.version | length == 0
  block:
    - name: Get latest php installed
      ansible.builtin.shell:
        cmd: 'set -o pipefail && ls -1 /etc/php/ | while read ver; do if [ -d "/etc/php/$ver/fpm" ]; then echo "$ver"; fi; done | tail -1 | sed -e "s/\\.//g"'
      args:
        executable: /bin/bash
      register: _php_version_str

    - name: Download latest cachetool installer if PHP is 8.1 or newer.
      ansible.builtin.get_url:
        url: "https://gordalina.github.io/cachetool/downloads/cachetool.phar"
        dest: "{{ cachetool_bin }}"
        mode: 0755
      when:
        - _php_version_str.stdout | int >= 81

    - name: Download cachetool version 8.5.0 installer if PHP is 8.0.
      ansible.builtin.get_url:
        url: "https://gordalina.github.io/cachetool/downloads/cachetool-8.5.0.phar"
        dest: "{{ cachetool_bin }}"
        mode: 0755
      when:
        - _php_version_str.stdout | int == 80

    - name: Download cachetool version 7.1.0 installer if PHP is 7.3 or newer.
      ansible.builtin.get_url:
        url: "https://gordalina.github.io/cachetool/downloads/cachetool-7.1.0.phar"
        dest: "{{ cachetool_bin }}"
        mode: 0755
      when:
        - _php_version_str.stdout | int >= 73
        - _php_version_str.stdout | int < 80

    - name: Download cachetool version 5.1.3 installer if PHP is 7.2.
      ansible.builtin.get_url:
        url: "https://gordalina.github.io/cachetool/downloads/cachetool-5.1.3.phar"
        dest: "{{ cachetool_bin }}"
        mode: 0755
      when:
        - _php_version_str.stdout | int == 72

    - name: Download cachetool version 4.1.1 installer if PHP is 7.1.
      ansible.builtin.get_url:
        url: "https://gordalina.github.io/cachetool/downloads/cachetool-4.1.1.phar"
        dest: "{{ cachetool_bin }}"
        mode: 0755
      when:
        - _php_version_str.stdout | int == 71

    - name: Download cachetool version 3.2.2 installer if PHP version is too old.
      ansible.builtin.get_url:
        url: "https://gordalina.github.io/cachetool/downloads/cachetool-3.2.2.phar"
        dest: "{{ cachetool_bin }}"
        mode: 0755
      when:
        - _php_version_str.stdout | int < 71

- name: "Download the specified {{ cachetool.version }} cachetool version installer."
  ansible.builtin.get_url:
    url: "https://gordalina.github.io/cachetool/downloads/cachetool-{{ cachetool.version }}.phar"
    dest: "{{ cachetool_bin }}"
    mode: 0755
  when:
    - deploy_operation == 'deploy'
    - cachetool.version is defined
    - cachetool.version | length > 0

# Set up cachetool adapter - needs to happen on every run so _cachetool_adapter is set.
- name: Get latest PHP version installed.
  ansible.builtin.shell:
    cmd: 'set -o pipefail && ls -1 /etc/php/ | while read ver; do if [ -d "/etc/php/$ver/fpm" ]; then echo "$ver"; fi; done | tail -1'
  args:
    executable: /bin/bash
  register: _php_version

- name: Set cachetool adapter specified or default to a TCP/IP port.
  ansible.builtin.set_fact:
    _cachetool_adapter: "{{ cachetool.adapter | default('--fcgi=127.0.0.1:90' + _php_version.stdout | replace('.','')) }}"

- name: Override cachetool adapter to be a Unix socket if requested.
  ansible.builtin.set_fact:
    _cachetool_adapter: "--fcgi=/var/run/php{{ _php_version.stdout | replace('.','') }}-fpm.sock"
  when:
    - cachetool.unix_socket
    - cachetool.adapter is not defined

- name: Ensure cachetool is working.
  ansible.builtin.command:
    cmd: "{{ cachetool_bin }} {{ _cachetool_adapter }} -n opcache:status"
  when: _php_version.stdout | length > 0
  register: opcache_status_check
  retries: "{{ cachetool.check_retries }}"
  delay: "{{ cachetool.check_delay }}"
  until: opcache_status_check.rc == 0
  failed_when: false
