---
# Drupal 8 ships drush with the website code so to use the drush_live_bin variable
- name: Clear Drupal cache.
  ansible.builtin.command:
    cmd: "{{ drush_live_bin }} -l {{ site.folder }} -y cr"
    chdir: "{{ live_symlink_dest }}/{{ webroot }}/sites/{{ site.folder }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site
  run_once: true
