---
npm:
  # npm/yarn
  executor: npm
  working_dir: "{{ deploy_path }}"
  # A list of commands to execute.
  # eg:
  # - install
  # - build-prod
  commands: []
  # Specify any additional symlink to create, with src (target) and dest (link).
  # src: can be either absolute or relative to the dest (eg. '/var/my_data', '/home/deploy/simplesaml', '../../../myconfig')
  # dest: can only be relative to the root of your repository (eg. 'www/themes/myassets', 'var/cache')
  # create: whether to create the target if it does not exists.
  #  - src: '/home/{{ deploy_user }}//{{ project_name }}_{{ build_type }}/simplesaml'
  #    dest: 'vendor/simplesamlphp/simplesamlphp/config'
  #  - src: '/var/simplesaml/etc'
  #    dest: 'vendor/simplesamlphp/simplesamlphp/config'
  symlinks: []
  # Specify any additional templates to generate, with src (template) and dest (file).
  # src: name of a template, in the "templates" dir relative to your playbook.
  # dest: can only be relative to the root of your repository (eg. 'www/config.php', 'var/mysettings.php')
  templates: []
