- name: Check if we have a SquashFS image from a previous successful build.
  ansible.builtin.stat:
    path: "{{ build_base_path }}/deploy_previous.sqsh"
  register: _deploy_code_revert_image
  when:
    - deploy_code.mount_sync is defined
    - deploy_code.mount_sync | length > 1
    - deploy_code.mount_type == "squashfs"

- name: Move previous SquashFS image back to be re-mounted.
  ansible.builtin.copy:
    remote_src: true
    force: true
    src: "{{ build_base_path }}/deploy_previous.sqsh"
    dest: "{{ build_base_path }}/deploy.sqsh"
  when:
    - deploy_code.mount_sync is defined
    - deploy_code.mount_sync | length > 1
    - deploy_code.mount_type == "squashfs"
    - _deploy_code_revert_image.stat.islnk is defined

- name: Check if we have a mount already.
  ansible.builtin.shell:
    cmd: "mount | grep {{ deploy_base_path }}"
  ignore_errors: true
  register: _deploy_code_mount_check
  when:
    - deploy_code.mount_sync is defined
    - deploy_code.mount_sync | length > 1
    - deploy_code.mount_type == "squashfs"

- name: Unmount existing and presumed bad SquashFS image.
  ansible.builtin.command:
    cmd: "umount -l {{ deploy_base_path }}"
  become: true
  when:
    - deploy_code.mount_sync is defined
    - deploy_code.mount_sync | length > 1
    - deploy_code.mount_type == "squashfs"
    - _deploy_code_mount_check is succeeded
    - _deploy_code_revert_image.stat.islnk is defined

- name: Reload any services that might be keeping the loop device busy.
  ansible.builtin.service:
    name: "{{ www_service }}"
    state: reloaded
  with_items: "{{ deploy_code.services }}"
  loop_control:
    loop_var: www_service
  become: true
  when:
    - deploy_code.mount_sync is defined
    - deploy_code.mount_sync | length > 1
    - deploy_code.mount_type == "squashfs"
    - _deploy_code_mount_check is succeeded
    - deploy_code.services | length > 0
    - _deploy_code_revert_image.stat.islnk is defined

- name: Mount SquashFS image from previous successful build.
  ansible.builtin.command:
    cmd: "mount {{ _deploy_code_revert_image }} {{ deploy_base_path }} -t squashfs -o loop"
  become: true
  when:
    - deploy_code.mount_sync is defined
    - deploy_code.mount_sync | length > 1
    - deploy_code.mount_type == "squashfs"
    - _deploy_code_revert_image.stat.islnk is defined
