---
- name: Get latest php installed
  ansible.builtin.shell:
    cmd: "ls /etc/php/ | tail -1"
  register: _php_version

- name: Clear opcache.
  command:
    cmd: "{{ cachetool_bin }} {{ cache_clear_opcache.adapter }} -n opcache:reset"
  when: cache_clear_opcache.clear_opcache

- name: Clear apcu.
  command:
    cmd: "{{ cachetool_bin }} {{ cache_clear_opcache.adapter }} -n apcu:cache:clear all"
  when: cache_clear_opcache.clear_apcu

- name: Clear stats.
  command:
    cmd: "{{ cachetool_bin }} {{ cache_clear_opcache.adapter }} -n stat:clear"
  when: cache_clear_opcache.clear_stat
