---
# cachetool_bin is set in the _init role.
- name: Clear opcache.
  ansible.builtin.command:
    cmd: "{{ cachetool_bin }} {{ _cachetool_adapter }} -n opcache:reset"
  when: cache_clear_opcache.clear_opcache

- name: Clear apcu.
  ansible.builtin.command:
    cmd: "{{ cachetool_bin }} {{ _cachetool_adapter }} -n apcu:cache:clear"
  when: cache_clear_opcache.clear_apcu

- name: Clear stats.
  ansible.builtin.command:
    cmd: "{{ cachetool_bin }} {{ _cachetool_adapter }} -n stat:clear"
  when: cache_clear_opcache.clear_stat
