---
- name: Pause StatusCake check.
  ansible.builtin.uri:
    url: "https://api.statuscake.com/v1/uptime/{{ domain.statuscake_check_id }}"
    method: PUT
    body_format: form-urlencoded
    body:
      paused: true
    headers:
      Authorization: "Bearer {{ domain.statuscake_api_key }}"
    status_code:
      - 200
      - 204
  when:
    - domain.statuscake_check_id is defined
    - domain.statuscake_check_id | length > 0
    - domain.statuscake_api_key is defined
    - domain.statuscake_api_key | length > 0
