---
# For some unknown reason, updating the field_user_data table did not work reliably,
# nor did drush upwd for the password.
# Loading the user directly is akward, but at least means we don't bypass entity update.
- name: Reset admin username.
  command:
    cmd: "{{ drush_bin }} php-eval '$admin = \\Drupal\\user\\Entity\\User::load(1); $admin->setUsername(\"{{ admin_creds.username }}\");$admin->save();' -l {{ site.folder }}"
    chdir: "{{ deploy_path }}/{{ webroot }}/sites/{{ site.folder }}"
  when:
    - admin_creds.username | length > 1

- name: Reset admin password.
  command:
    cmd: "{{ drush_bin }} php-eval '$admin = \\Drupal\\user\\Entity\\User::load(1); $admin->setPassword(\"{{ admin_creds.password }}\");$admin->save();' -l {{ site.folder }}"
    chdir: "{{ deploy_path }}/{{ webroot }}/sites/{{ site.folder }}"
  when:
    - admin_creds.password | length > 1
