---
cron_mysql_backup:
  dumps_directory: "/home/{{ deploy_user }}/shared/{{ project_name }}_{{ build_type }}/db_backups/mysql/regular"
  keep: 10
  mysqldump_params: "{{ _mysqldump_params }}" # set in _init but you can override here
