---
# For some reason D7 drush doesn't respect 'chdir' with command, using shell instead.
- name: Check if Ctools module is enabled.
  ansible.builtin.shell:
    cmd: "{{ drush_bin }} pm-info ctools | grep ':  enabled' | wc -l"
    chdir: "{{ deploy_path }}/{{ webroot }}/sites/{{ site.folder }}"
  register: ctools_enabled

- name: Revert Drupal configuration from Ctools.
  ansible.builtin.shell:
    cmd: "{{ drush_bin }} -y ctools-export-revert --all"
    chdir: "{{ deploy_path }}/{{ webroot }}/sites/{{ site.folder }}"
  when: ctools_enabled.stdout == "1"
