---
# Puts site(s) offline.
maintenance_mode:
  # Where do we apply maintenance - can be invoked more than one time for different purposes.
  # - nginx: serves a static maintenance page
  # - drupal-core: application level
  # - statuscake: disables a StatusCake check
  # @todo - haproxy: serves a static maintenance page.
  # @todo - drupal-read-only: application level via readonly module.
  mode: "nginx"
  # - offline: puts the site offline
  # @todo - restricted: put the site offline except for whitelist (nginx/haproxy only)
  # - online: brings the site back online.
  operation: "offline"