---
- name: Perform NPM steps.
  command:
    cmd: "{{ npm.executor }} {{ npm_command }}"
    chdir: "{{ npm.working_dir }}"
  with_items: "{{ npm.commands }}"
  loop_control:
    loop_var: npm_command
  when: deploy_operation == 'deploy'

- name: Generate additional templates.
  template:
    src: "{{ template.src }}"
    dest: "{{ deploy_path }}/{{ template.dest }}"
  with_items: "{{ npm.templates }}"
  loop_control:
    loop_var: template
  when:
    - npm.templates | length
    - deploy_operation == 'deploy'

- name: Create additional symlinks.
  file:
    src: "{{ link.src }}"
    dest: "{{ deploy_path }}/{{ link.dest }}"
    state: link
    force: "{{ link.force | default(false) }}"
  with_items: "{{ npm.symlinks }}"
  loop_control:
    loop_var: link
  when:
    - npm.symlinks | length
    - deploy_operation == 'deploy'