---
- name: Grab mysql credentials.
  ansible.builtin.fetch:
    src: "{{ database.credentials_file }}"
    dest: "{{ _ce_deploy_build_dir }}/mysql_backup_credentials.ini"
    flat: true

# Credentials for "managing" databases.
- ansible.builtin.set_fact:
    _mysql_host: "{{ lookup('ini', 'host section=client file={{ _ce_deploy_build_dir }}/mysql_backup_credentials.ini') }}"
- ansible.builtin.set_fact:
    _mysql_user: "{{ lookup('ini', 'user section=client file={{ _ce_deploy_build_dir }}/mysql_backup_credentials.ini') }}"
- ansible.builtin.set_fact:
    _mysql_password: "{{ lookup('ini', 'password section=client file={{ _ce_deploy_build_dir }}/mysql_backup_credentials.ini') }}"

- ansible.builtin.include_tasks: "cleanup-{{ mysql_backup.handling }}.yml"

- name: Delete mysql users.
  community.mysql.mysql_user:
    name: "{{ database.user }}_{{ item }}"
    host_all: true
    state: absent
    login_host: "{{ _mysql_host }}"
    login_user: "{{ _mysql_user }}"
    login_password: "{{ _mysql_password }}"
  with_sequence: start={{ [previous_build_number | int - mysql_backup.cleanup_history_depth, 0] | max }}  end={{ [previous_build_number | int - mysql_backup.keep, 0] | max }}
  when: mysql_backup.credentials_handling == 'rotate'
  run_once: true
