---
- name: Delete MySQL databases.
  community.mysql.mysql_db:
    name: "{{ database.database }}_{{ item }}"
    state: absent
    login_host: "{{ _mysql_host }}"
    login_user: "{{ _mysql_user }}"
    login_password: "{{ _mysql_password }}"
    login_unix_socket: "{{ mysql_backup.mysql_unix_socket | default(omit) }}"
  with_items: "{{ _build_numbers_to_delete }}"  # set in _init role
