---
- set_fact:
    _mysql_build_database_name: "{{ database.database }}"
- set_fact:
    _mysql_previous_build_database_name: "{{ database.database }}"

- name: Create initial database.
  mysql_db:
    name: "{{ _mysql_build_database_name }}"
    state: present
    login_host: "{{ _mysql_host }}"
    login_user: "{{ _mysql_user }}"
    login_password: "{{ _mysql_password }}"
  when: previous_build_number == 0
  run_once: true

- name: Take a database dump.
  shell: "mysqldump --defaults-extra-file={{ database.credentials_file }} {{ mysql_backup.mysqldump_params }} {{ database.database }} | bzip2 > {{ mysql_backup.dumps_directory }}/{{ _mysql_host }}/{{ database.database }}-{{ previous_build_number }}.sql.bz2"
  when: previous_build_number > 0
  run_once: true
