---
- ansible.builtin.set_fact:
    _mysql_build_database_name: "{{ database.database }}"
- ansible.builtin.set_fact:
    _mysql_previous_build_database_name: "{{ database.database }}"

- name: Create initial database.
  community.mysql.mysql_db:
    name: "{{ _mysql_build_database_name }}"
    state: present
    login_host: "{{ _mysql_host }}"
    login_user: "{{ _mysql_user }}"
    login_password: "{{ _mysql_password }}"
  when: previous_build_number == 0
  run_once: true
