---
- name: Define Drush path.
  set_fact:
    drush_bin: "{{ drush_bin | default('{{ bin_directory }}/drush-{{ drush.version }}/drush') }}"

- name: Ensure we have Drush binary.
  import_role:
    name: cli/drush
