---
- name: Pause so as to not hammer the AWS API.
  ansible.builtin.pause:
    seconds: "{{ asg_management.pause }}"

- name: Empty the target list.
  ansible.builtin.set_fact:
    _target_health_list: []

- name: Fetch target instance data.
  when:
    - _target_group.target_groups | length > 0
    - asg_management.profile is not defined
  block:
    - name: Fetch raw target health data with the AWS CLI.
      ansible.builtin.command: >-
          aws elbv2 describe-target-health
          --target-group-arn {{ _target_group.target_groups[0].target_group_arn }}
          --region {{ asg_management.region }}
      register: _target_health

    - name: Convert raw JSON output from CLI to YAML for ease of use.
      ansible.builtin.set_fact:
        _target_health_yaml: "{{ _target_health.stdout | from_json }}"

- name: Fetch target instance data with a boto profile.
  when:
    - _target_group.target_groups | length > 0
    - asg_management.profile is defined
    - asg_management.profile | length > 0
  block:
    - name: Fetch raw target health data with the AWS CLI via a specified boto profile.
      ansible.builtin.command: >-
          aws elbv2 describe-target-health
          --target-group-arn {{ _target_group.target_groups[0].target_group_arn }}
          --region {{ asg_management.region }}
          --profile {{ asg_management.profile }}
      register: _target_health_boto

    - name: Convert raw JSON output from CLI to YAML for ease of use.
      ansible.builtin.set_fact:
        _target_health_yaml: "{{ _target_health_boto.stdout | from_json }}"

- name: Make a list of all the 'healthy' instances.
  ansible.builtin.set_fact:
    _target_health_list: "{{ _target_health_list + [ item.TargetHealth.State ] }}"
  with_items: "{{ _target_health_yaml.TargetHealthDescriptions }}"
  when: item.TargetHealth.State == 'healthy'

- name: Run again if the number of 'healthy' instances does not match the total.
  ansible.builtin.include_tasks: "./asg_target_health.yml"
  when: (_target_health_yaml.TargetHealthDescriptions | length) != (_target_health_list | length)
