---
- name: Define cron job command.
  ansible.builtin.set_fact:
    _cron_job_command: "cd {{ live_symlink_dest }}/{{ webroot }}/sites/{{ site.folder }} && {{ drupal.drush_location }} {{ entry.job }}"

- name: Define cron job command if deferred (ASG).
  ansible.builtin.set_fact:
    _cron_job_command: "cd {{ _ce_deploy_base_dir }} && {{ _ce_deploy_ansible_location }} {{ drupal.defer_target }} -m shell -a \"{{ _cron_job_command }}\" > /dev/null"
  when:
    - drupal.defer is defined
    - drupal.defer
    - drupal.defer_target is defined
    - drupal.defer_target | length > 0

- name: Add dev null redirection (for non-deferred).
  ansible.builtin.set_fact:
    _cron_job_command: "{{ _cron_job_command }} > /dev/null"
  when:
    - drupal.defer is not defined or not drupal.defer

- name: Define cron job command for differing deploy users.
  ansible.builtin.set_fact:
    _cron_job_command: "{{ _cron_job_command }} --extra-vars '{\"become\":true,\"become_user\":\"{{ www_user }}\"}'"
  when:
    - www_user != deploy_user
    - drupal.defer is defined
    - drupal.defer

- name: Set global MAILTO entry if it exists
  ansible.builtin.cron:
    name: MAILTO
    env: true
    job: "{{ drupal.cron_mailto }}"
    state: present
  when: drupal.cron_mailto is defined
  delegate_to: "{{ 'localhost' if drupal.defer else inventory_hostname }}"
  become: true

#- name: Remove existing MAILTO entry (if any)
#  community.general.cronvar:
#    name: MAILTO
#    state: absent
#  delegate_to: "{{ 'localhost' if drupal.defer else inventory_hostname }}"

#- name: Set global MAILTO for cron jobs (if defined)
#  community.general.cronvar:
#    name: MAILTO
#    value: "{{ drupal.cron_mailto | default(omit) }}"
#    state: present
#  when: drupal.cron_mailto is defined and drupal.cron_mailto | length > 0
#  delegate_to: "{{ 'localhost' if drupal.defer else inventory_hostname }}"

- name: Setup Drupal cron tasks on app server.
  ansible.builtin.cron:
    name: "{{ project_name }}_{{ site.folder }}_{{ build_type }}_{{ entry.job }}"
    minute: "{{ entry.minute }}"
    hour: "{{ entry.hour | default(omit) }}"
    day: "{{ entry.day | default(omit) }}"
    weekday: "{{ entry.weekday | default(omit) }}"
    month: "{{ entry.month | default(omit) }}"
    job: "{{ _cron_job_command }}"
    state: present
    disabled: "{{ entry.disabled | default(omit) }}"
    cron_file: "{{ entry.file | default(omit) }}"
    user: "{{ entry.file_user | default(omit) }}"
  delegate_to: "{{ 'localhost' if drupal.defer else inventory_hostname }}"
  become: "{{ true if entry.file is defined else false }}"
