---
files_sync:
  directories:
    - source:
        # Location of the files to sync from.
        files_dir: "/home/{{ deploy_user }}/shared/{{ project_name }}_prod/assets/{{ project_name }}_prod_default_public_files"
        # Host that can connect to the database.
        host: "localhost"
        # For "rolling builds", so we can compute the database name.
        build_id: mybuildprod
      target:
        # Location of the files to sync to.
        files_dir: "/home/{{ deploy_user }}/shared/{{ project_name }}_dev/assets/{{ project_name }}_dev_default_public_files"
        build_id: mybuilddev
