---
- name: Generate project specific configuration.
  ansible.builtin.include_role:
    name: "config_generate/config_generate-{{ project_type }}"
  when: deploy_operation == 'deploy'

- name: Generate additional templates.
  ansible.builtin.template:
    src: "{{ template.src }}"
    dest: "{{ deploy_path }}/{{ template.dest }}"
  with_items: "{{ config_generate.templates }}"
  loop_control:
    loop_var: template
  when:
    - config_generate.templates | length
    - deploy_operation == 'deploy'

- name: Create additional symlinks.
  ansible.builtin.file:
    src: "{{ link.src }}"
    dest: "{{ deploy_path }}/{{ link.dest }}"
    state: link
  with_items: "{{ config_generate.symlinks }}"
  loop_control:
    loop_var: link
  when:
    - config_generate.symlinks | length
    - deploy_operation == 'deploy'