---
- name: Clear Drupal cache.
  ansible.builtin.command:
    cmd: "{{ drush_bin }} -l {{ site_drupal.folder }} -y cr"
    chdir: "{{ deploy_path }}/{{ webroot }}/sites/{{ site_drupal.folder }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site_drupal
  run_once: true
  register: _drush_output

- name: Show drush output.
  ansible.builtin.debug:
    msg: "{{ _drush_output }}"
  when: drupal.drush_verbose_output
