---
- name: Override paths for squashfs build cleanup step.
  block:
    - name: Override path to drush binary.
      set_fact:
        drush_bin: "{{ drush_live_bin }}"

    - name: Override deploy_path.
      set_fact:
        deploy_path: "{{ live_symlink_dest }}"
  when:
    - deploy_code.mount_type is defined
    - deploy_code.mount_type == "squashfs"
    - deploy_operation == "cleanup"

- name: Clear Drupal cache.
  ansible.builtin.command:
    cmd: "{{ drush_bin }} -l {{ site_drupal.folder }} -y cr"
    chdir: "{{ deploy_path }}/{{ webroot }}/sites/{{ site_drupal.folder }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site_drupal
  run_once: true
  register: _drush_output

- name: Show drush output.
  ansible.builtin.debug:
    msg: "{{ _drush_output }}"
  when: drupal.drush_verbose_output

- name: Truncate SQL table 'cache_container'.
  block:
    - name: Truncate table 'cache_container'.
      ansible.builtin.command:
        cmd: "{{ drush_bin }} sql-query 'TRUNCATE TABLE cache_container'"
        chdir: "{{ deploy_path }}/{{ webroot }}/sites/{{ site_drupal.folder }}"
      become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
      become_user: "{{ www_user }}"
      with_items: "{{ drupal.sites }}"
      loop_control:
        loop_var: site_drupal
      run_once: true
      register: _drush_output

    - name: Show drush output.
      ansible.builtin.debug:
        msg: "{{ _drush_output }}"
      when:
        - drupal.drush_verbose_output
  when:
    - drupal.truncate_cache_table
    - deploy_code.mount_type is defined
    - deploy_code.mount_type == "squashfs"
    - deploy_operation == "cleanup"
