---
- name: Apply Drupal database updates.
  ansible.builtin.command:
    cmd: "{{ drush_bin }} -l {{ site.folder }} -y updb"
    chdir: "{{ live_symlink_dest }}/{{ webroot }}/sites/{{ site.folder }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site

# This only runs if the sync_config_import variable is not defined or it is defined and is true. If it's defined and false, this won't run.
- name: Import configuration.
  ansible.builtin.command:
    cmd: "{{ drush_bin }} -l {{ site.folder }} -y {{ site.config_import_command }}"
    chdir: "{{ live_symlink_dest }}/{{ webroot }}/sites/{{ site.folder }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site
  when:
    - site.config_import_command
    - site.sync_config_import is not defined or site.sync_config_import

- name: Clear the cache.
  ansible.builtin.include_role:
    name: "sync/drupal_sync_tasks/cache_clear/cache_clear-{{ project_type }}"
