---
- name: Register file sync location.
  ansible.builtin.set_fact:
    file_sync_path: "{{ files.source.temp_dir }}/{{ files.source.build_id }}_{{ build_number }}"

- name: Create a temporary directory for source files on localhost.
  ansible.builtin.file:
    path: "{{ file_sync_path }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  delegate_to: localhost
  run_once: true

- name: Copy the source files onto the deploy server.
  ansible.builtin.command:
    cmd: "rsync -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' -aHPv {{ files.source.host }}:{{ files.source.files_dir }}/ {{ file_sync_path }}/"
  delegate_to: "localhost"
  run_once: true

- name: Copy the source files from the deploy server onto the destination server.
  ansible.builtin.command:
    cmd: "rsync -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' -aHPv {{ file_sync_path }}/ {{ ansible_play_hosts[0] }}:{{ files.target.files_dir }}/"
  delegate_to: "localhost"
  run_once: true
