---
- name: Check if we already have a global Drush.
  ansible.builtin.stat:
    path: "{{ drush_bin }}"
  register: drush_global
  when:
    - deploy_operation == 'deploy'

- name: Ensure bin directory exists.
  ansible.builtin.file:
    path: "{{ drush_bin | dirname }}"
    state: directory
  when:
    - deploy_operation == 'deploy'
    - not drush.use_vendor
  register: drush_global_directory

- name: Check if installed Drush version match.
  ansible.builtin.shell: "{{ drush_bin }} --version | grep -o '[0-9]\\.[0-9]\\.[0-9]'"
  register: drush_global_version
  when:
    - deploy_operation == 'deploy'
    - drush_global.stat.exists
    - not drush.use_vendor

# @TODO - we can remove this when Drupal 7 reaches EOL.
- name: Download Drush installer for Drupal 7.
  ansible.builtin.get_url:
    url: "https://github.com/drush-ops/drush/releases/download/{{ drush.version }}/drush.phar"
    dest: "{{ drush_bin }}"
    mode: 0755
    force: true
  when:
    - deploy_operation == 'deploy'
    - not drush.use_vendor
    - not drush_global.stat.exists or not drush_global_version.stdout == drush.version
    - drush.version < 9

- name: Download Drush archive.
  ansible.builtin.get_url:
    url: "https://github.com/drush-ops/drush/archive/refs/tags/{{ drush.version }}.tar.gz"
    dest: /tmp/drush.tar.gz
    mode: 0755
    force: true
  when:
    - deploy_operation == 'deploy'
    - not drush.use_vendor
    - not drush_global.stat.exists or not drush_global_version.stdout == drush.version
    - drush.version >= 9

- name: "Extract drush.tar.gz into {{ drush_bin | dirname }}"
  ansible.builtin.unarchive:
    src: /tmp/drush.tar.gz
    dest: "{{ drush_bin | dirname }}"
    mode: 0755
  when:
    - deploy_operation == 'deploy'
    - not drush.use_vendor
    - not drush_global.stat.exists or not drush_global_version.stdout == drush.version
    - drush.version >= 9

- name: Create .bashrc file if it does not exist
  ansible.builtin.file:
    path: "/home/{{ deploy_user }}/.bashrc"
    state: touch
  when:
    - deploy_operation == 'deploy'

- name: Add drush directory to the .bashrc file
  ansible.builtin.lineinfile:
    path: "/home/{{ deploy_user }}/.bashrc"
    line: "export PATH=\"$PATH:{{ drush_global_directory.path }}\""
  when:
    - drush_global_directory.path is defined
    - deploy_operation == 'deploy'

- name: Trigger Drush init tasks.
  ansible.builtin.command: "{{ drush_bin }} init -y"
  when:
    - deploy_operation == 'deploy'
    - not drush.use_vendor
    - not drush_global.stat.exists or not drush_global_version.stdout == drush.version