---
# For some reason D7 drush doesn't respect 'chdir' with command, using shell instead.
- name: Clear Drupal 7 cache.
  ansible.builtin.shell:
    cmd: "{{ drush_bin }} -l {{ site.folder }} -y cc all"
    chdir: "{{ live_symlink_dest }}/{{ webroot }}/sites/{{ site.folder }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  with_items: "{{ drupal.sites }}"
  loop_control:
    loop_var: site
  run_once: true
