---
- name: Execute a container deployment.
  ansible.builtin.include_tasks:
    file: "action-{{ deploy_container.action }}.yml"
  when: deploy_operation == 'deploy'

- name: Cleanup dangling containers.
  ansible.builtin.include_tasks:
    file: action-cleanup.yml
  when: deploy_operation == 'cleanup'
