- name: Gather private subnet information.
  amazon.aws.ec2_vpc_subnet_info:
    profile: "{{ deploy_container.aws_ecs.aws_profile }}"
    region: "{{ deploy_container.aws_ecs.region }}"
    filters:
      vpc-id: "{{ _aws_ecs_cluster_vpc_id }}"
      tag:Name: "{{ subnet }}"
  register: _aws_ecs_cluster_private_subnet
  delegate_to: localhost

- name: Add private subnet to the list.
  ansible.builtin.set_fact:
    _aws_ecs_cluster_private_subnets_ids: "{{ _aws_ecs_cluster_private_subnets_ids + [ _aws_ecs_cluster_private_subnet.subnets[0].subnet_id ] }}"
