---

- name: Sync databases.
  ansible.builtin.include_role:
    name: "sync/database_sync/database_sync-{{ engine }}"
  with_items: "{{ database_sync.engines }}"
  loop_control:
    loop_var: engine
  when: deploy_operation == 'deploy'