---
cron_ecs:
  container_tag: latest # tag will take format container_name:container_tag
  container_force_build: true # force Docker to build and tag a new image
  docker_registry_name: index.docker.io/example # combines with container_name to make the full registry name, docker_registry_name/container_name
  docker_registry_url: https://index.docker.io/example
  docker_build_dir: "{{ _ce_deploy_build_dir }}"
  dockerfile_template: Dockerfile.j2 # provide a templates directory next to your playbook and change this to match your Dockerfile template name
  # Requires the deploy IAM user to have the managed EC2InstanceProfileForImageBuilderECRContainerBuilds policy attached
  aws_ecr:
    region: eu-west-1
    aws_profile: example
  # Requires the deploy IAM user to have the managed AmazonECS_FullAccess and ElasticLoadBalancingFullAccess policies attached
  # Note, you can if you wish make more restrictive roles and policies
  drupal_cron_entrypoint: "sh -c"
  drupal_cron_command:
    - "cd sites/{{ site.folder }} && ../../../vendor/bin/drush {{ entry.job }}"
  aws_ecs:
    region: eu-west-1
    aws_profile: example
    tags: {}
    vpc_name: example
    # vpc_id: vpc-XXXXXXX # optionally specify VPC ID to use
    # security_groups: [] # list of security groups, accepts names or IDs
    cluster_name: example-cluster
    task_definition_force_create: false # creates a task definition revision every time if set to true
    task_execution_role_arn: "arn:aws:iam::000000000000:role/ecsTaskExecutionRole" # ARN of the IAM role to run the task as, must have access to the ECR repository if applicable
    # service_enable_ssm: false # set to true to allow arbitrary command execution on containers via the AWS API
    # task_role_arn: "" # required if you set service_enable_ssm to true
    task_count: 1
    # service_force_refresh: false # forces a refresh of all containers if set to true
    cpu: 512 # these values can be set globally or per container
    memory: 1024
    launch_type: FARGATE
    network_mode: awsvpc
    # volumes: [] # list of additional volumes to attach
