---
# Default Matomo role.

- ansible.builtin.import_role:
    name: _init
- ansible.builtin.import_role:
    name: deploy_code
- ansible.builtin.import_role:
    name: database_backup
- ansible.builtin.import_role:
    name: config_generate
- ansible.builtin.import_role:
    name: database_apply
- ansible.builtin.import_role:
    name: live_symlink
- ansible.builtin.import_role:
    name: cache_clear/cache_clear-opcache
- ansible.builtin.import_role:
    name: cache_clear/cache_clear-matomo
- ansible.builtin.import_role:
    name: cron/cron_database_backup
- ansible.builtin.import_role:
    name: cron/cron_matomo
- ansible.builtin.import_role:
    name: _exit
