name: Linting

# Run this workflow every time a new commit pushed to your repository
on: pull_request

jobs:
  run-linting:
    if: ${{ always() }}
    name: Linting
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code.
        uses: actions/checkout@v4

      # Linter checks.
      - name: Install linters.
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible-lint yamllint shellcheck

      - name: Run ansible-lint.
        run: find ./roles -name "*.yml"  | xargs ansible-lint

      - name: Run yamllint.
        run: yamllint ./roles

      - name: Run shellcheck.
        run: cd scripts && shellcheck *.sh
