---
# @todo this needs refactoring for multisite.
- name: Enable maintenance mode.
  ansible.builtin.command:
    cmd: "{{ drush_bin }} -l {{ site.folder }} state:set system.maintenance_mode 1 --input-format=integer"
    chdir: "{{ live_symlink_dest }}/{{ webroot }}/sites/{{ site.folder }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  when:
    - previous_build_number > 0
    - project_type == 'drupal8'

- name: Enable maintenance mode D7.
  ansible.builtin.command:
    cmd: "{{ drush_bin }} -l {{ site.folder }} vset maintenance_mode 1"
    chdir: "{{ live_symlink_dest }}/{{ webroot }}/sites/{{ site.folder }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  when:
    - previous_build_number > 0
    - project_type == 'drupal7'
