---
- name: Enable maintenance mode.
  ansible.builtin.command:
    cmd: "{{ drush_live_bin }} -l {{ site.folder }} state:set system.maintenance_mode 1 --input-format=integer --root {{ live_symlink_dest }}/{{ webroot }}/sites/{{ site.folder }}"
  args:
    chdir: "{{ live_symlink_dest }}/{{ webroot }}/sites/{{ site.folder }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  when:
    - previous_build_number > 0
    - project_type == 'drupal8'

# For some reason D7 drush doesn't respect 'chdir' with command, using shell instead.
- name: Enable maintenance mode D7.
  ansible.builtin.shell:
    cmd: "{{ drush_live_bin }} -l {{ site.folder }} vset maintenance_mode 1"
    chdir: "{{ live_symlink_dest }}/{{ webroot }}/sites/{{ site.folder }}"
  become: "{{ 'no' if www_user == deploy_user else 'yes' }}"
  become_user: "{{ www_user }}"
  when:
    - previous_build_number > 0
    - project_type == 'drupal7'
